pipeline{
    agent any
    environment{
    ECR_REPOSITORY = credentials('ECR_REPOSITORY')
    AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
    AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    AWS_REGION= credentials('AWS_REGION')
    }

    stages{
        stage('Continuous Integration'){
            steps{
                script{
                echo "Linting repository"
                echo "Running unit tests"
                }
            }
        }

        stage('Login to ECR'){
            steps{
                script{
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                }
            }
        }

        stage('Build Image'){
            steps{
                script{
                    sh "docker build -t ${ECR_REPOSITORY}:latest ."
                }
            }
        }

        stage("Push Image"){
            steps{
                script{
                    sh "docker push ${ECR_REPOSITORY}:latest"
                }
            }
        }

        stage("Continuous Deployment"){
            steps{
                sshagent("ssh_key"){
                    sh "ssh -o StrictHostKeyChecking=no -l ubuntu 44.215.220.137 'cd /home/ubuntu/ && wget https://raw.githubusercontent.com/natek-1/Chest-CT-Scan-Classification/main/docker-compose.yml && export IMAGE_NAME=${ECR_REPOSITORY}:latest && aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com && docker compose up -d '"
                }
            }
        }

        post{
            always {
                sh 'docker system prune -f'
            }
        }
    }
}