artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view
  local_file: data.zip

base_model:
  root_dir: artifacts/base_model
  base_model_filename: base_model.h5
  updated_base_model_filename: base_model_updated.h5

training:
  root_dir: artifacts/training
  training_data_path: artifacts/data_ingestion/Chest-CT-Scan-data
  pretrained_model_path: artifacts/base_model/base_model_updated.h5
  model_filename: model.h5


